VENDOR = gentoo

CURDATE = $(shell date +%Y%m%d)

CACHEDIR = /sysimage/cache
OUTDIR = $(HOME)/sysimage/stateless

COMPRESS = zstd -19 -T0 -v

IMAGE_VAR_ARCH    = amd64
IMAGE_VAR_VARIANT = systemd-mergedusr

IMAGE_VAR_OVERLAYS = local:git:https://github.com/legionus/local-overlay

IMAGE_VAR_EMERGE_QUIET = true
IMAGE_VAR_EMERGE_JOBS = 3

IMAGE_PREFILES = $(CURDIR)/../files
COPY_TREE      = $(CURDIR)/../files

BASEIMAGE_SCRIPT = $(CURDIR)/../baseimage.sh
