VENDOR = gentoo

CURDATE = $(shell date +%Y%m%d)

CACHEDIR = /sysimage/cache
OUTDIR = $(HOME)/sysimage/stateless
WORKDIR = $(shell realpath $(CURDIR)/../.work)

USE_SQUASHFS = true
SQUASHFS_ARGS = -b 1M -comp xz

IMAGE_VAR_ARCH    = amd64
IMAGE_VAR_VARIANT = systemd

IMAGE_VAR_DONT_UPDATE_REPOS = 1
IMAGE_VAR_CACHE_REPOS = 1

IMAGE_VAR_EMERGE_QUIET = true
IMAGE_VAR_EMERGE_JOBS = 12
IMAGE_VAR_EMERGE_IGNORE_COLLISIONS = 1

INSTRUMENTAL_FILES = $(CURDIR)/../instrumental-files
INSTRUMENTAL_PACKAGES2 = \
	dev-vcs/git \
	sys-fs/squashfs-tools \
	sys-fs/btrfs-progs

IMAGE_PREFILES = $(CURDIR)/../files
COPY_TREE      = $(CURDIR)/../files
