#!/bin/sh -efu

kvers="$(rpm -qa 'kernel-image*' \
	    --qf '%{installtime} %{version}-%{name}-%{release}\n' \
	| sort -n \
	| cut -f 2 -d ' ' \
	| sed 's/kernel-image-//')"

[ -n "$kvers" ] || {
	echo "no kernel version identified" >&2
	exit 1
}

for kver in $kvers; do
	depmod -a "$kver"
done
