#!/bin/sh -efu

kvers="$(rpm -qa 'kernel-image*' \
	    --qf '%{installtime} %{version}-%{name}-%{release}\n' \
	| sort -n \
	| cut -f 2 -d ' ' \
	| sed 's/kernel-image-//')"

[ -n "$kvers" ] ||
	fatal "no kernel version identified"

cat > /etc/initrd-tmp.mk <<@@@
AUTODETECT =
MOUNTPOINTS = \
        /

MODULES_ADD += \
        fs-ext4 \
        pci:v000015B7d00005009sv000015B7sd00005009bc01sc08i02

FEATURES += \
        add-modules add-udev-rules cleanup compress gpu-drm kbd \
        network rdshell rootfs system-glibc ucode

COMPRESS = zstd

FEATURES += pipeline pipeline-stateless
@@@

for kver in $kvers; do
	make-initrd -c /etc/initrd-tmp.mk -N -k "$kver"
	chmod +r /boot/initrd-"$kver".img
done
