#!/bin/bash -eu

kvers=()

for kern in /boot/vmlinuz-*; do
	[ -e "$kern" ] || continue
	kvers+=("${kern#/boot/vmlinuz-}")
done

if [ -z "${kvers[*]}" ]; then
	for kern in /boot/kernel-*; do
		[ -e "$kern" ] || continue
		kvers+=("${kern#/boot/kernel-}")
	done
fi

if [ -z "${kvers[*]}" ] && [ -d /boot/loader/entries ]; then
	kvers+=( `sed -rn 's#^version[[:space:]]+##p' /boot/loader/entries/*.conf` )
fi

if [ -z "${kvers[*]}" ]; then
	echo "no kernel version identified" >&2
	exit 1
fi

cat > /tmp/initrd.mk <<@@@
AUTODETECT =
MOUNTPOINTS = /
MODULES_ADD += fs-ext4 fs-squashfs ${INFO_MODALIAS-} ${INFO_MODULES_ADD-}
FEATURES += \
        add-modules add-udev-rules cleanup compress \
        rdshell rootfs system-glibc \
        ${INFO_FEATURES-}

FEATURES += pipeline pipeline-stateless
COMPRESS = zstd
@@@

for kver in "${kvers[@]}"; do
	make-initrd -c /tmp/initrd.mk -N -k "$kver"
	chmod +r /boot/initramfs-"$kver".img
	mv -f -- /boot/initramfs-"$kver".img /boot/initrd-"$kver".img
done
