#!/bin/sh -eu

chmod 0755 /

rm -rf /var/lock /var/run /var/tmp
ln -s /run/lock /var/lock
ln -s /run /var/run
ln -s /tmp /var/tmp

if [ ! -d /home/root ]; then
	mv -T /root /home/root
	ln -s home/root /root
fi

sed -i -r -e 's#([[:space:]])/var/run/#\1/run/#g' \
	/etc/tmpfiles.d/*.conf \
	/lib/tmpfiles.d/*.conf \
	#

mkdir -p -- \
	/sysimage/mutable \
	/sysimage/stateless
