#!/bin/sh -efu

chmod 0755 /

rm -rf /var/lock /var/run /var/tmp
ln -s /run/lock /var/lock
ln -s /run /var/run
ln -s /tmp /var/tmp

mv -T /root /home/root
ln -s home/root /root

mkdir -p -- \
	/sysimage/mutable \
	/sysimage/stateless
