#!/bin/sh -efu

SOURCE_DATE_EPOCH="$(rpm -qa --qf '[%{FILEMTIMES}\n]' | sort -n | tail -1)"

[ -z "${GLOBAL_SOURCE_DATE_EPOCH-}" ] ||
	[ "$GLOBAL_SOURCE_DATE_EPOCH" -lt "$SOURCE_DATE_EPOCH" ] ||
		SOURCE_DATE_EPOCH="$GLOBAL_SOURCE_DATE_EPOCH"

DATE="$(date -d "@$SOURCE_DATE_EPOCH" 2>/dev/null)"
echo "SOURCE_DATE_EPOCH: $DATE ($SOURCE_DATE_EPOCH)"

(umask 222; echo "$SOURCE_DATE_EPOCH" > /.SOURCE_DATE_EPOCH)

# mandb seems to be completely unreproducible
find /var/cache/man -type f -name index.db -delete
