#!/bin/sh -eu

export LC_ALL=C

[ -d /etc/control.d ] ||
	exit 0

facilities=
for state in $INFO_CONTROL_STATES; do
	control "${state%%:*}" "${state##*:}"
	facilities="$facilities ${state%%:*}"
done

cd /etc/control.d/facilities/

rc=0
for f in *; do
	for ff in $facilities; do
		[ "$f" != "$ff" ] ||
			continue 2
	done
	echo "${0##*/} $f facility is not covered" >&2
	rc=1
done

exit "$rc"
