#!/bin/sh -efu

# SC2250: Prefer putting braces around variable references even when not strictly required.
# SC2039: In POSIX sh, brace expansion is undefined.
# shellcheck enable=all disable=SC2250,SC2039

PROG="${0##*/}"

export LC_ALL=C

tmpdir=
cleanup_tmpdir()
{
        [ -z "$tmpdir" ] || rm -rf -- "$tmpdir"
        exit "$@"
}

tmpdir=/tmp/"$PROG"
mkdir -p "$tmpdir"
trap 'cleanup_tmpdir $?' EXIT
trap 'exit 143' HUP INT QUIT PIPE TERM

cat >"$tmpdir"/suid.allowed <<@@@
4510 root:messagebus /lib/dbus-1/dbus-daemon-launch-helper
4710 root:vmusers /usr/lib/lxc/lxc-user-nic
4710 root:vmusers /usr/libexec/qemu-bridge-helper
4710 root:wheel /bin/su
4710 root:xgrp /usr/bin/Xorg
@@@

cat >"$tmpdir"/sgid.allowed <<@@@
2711 root:_gnupg /usr/bin/gpg
2711 root:chkpwd /usr/bin/vlock
2711 root:iputils /usr/libexec/ping/ping
2711 root:postdrop /usr/libexec/postfix/postqueue/postqueue
2711 root:postdrop /usr/sbin/postdrop
2711 root:proc /usr/bin/netlist
2711 root:screen /usr/bin/screen
2711 root:shadow /usr/bin/passwd
2711 root:shadow /usr/lib/chkpwd/tcb_chkpwd
2711 root:shadow /usr/lib/screen/tcb_chkpwd
2711 root:sshagent /usr/bin/ssh-agent
2711 root:tty /usr/bin/wall
2711 root:utempter /usr/bin/xterm
2711 root:utmp /usr/lib/screen/utempter
2711 root:utmp /usr/lib/utempter/utempter
@@@

dirs="$(set +f; printf '%s\n' /* | grep -Exv '/(dev|proc|sys)')"

# shellcheck disable=SC2086
find $dirs -type f \( -perm /4000 \) -printf '%m %u:%g %p\n' \
	>"$tmpdir"/suid.exists

# shellcheck disable=SC2086
find $dirs -type f \( -perm /2000 \) -printf '%m %u:%g %p\n' \
	>"$tmpdir"/sgid.exists

sort -u -o "$tmpdir"/suid.exists{,}
sort -u -o "$tmpdir"/sgid.exists{,}

diff -u "$tmpdir"/suid.{allowed,exists}
diff -u "$tmpdir"/sgid.{allowed,exists}

# fakeroot doesn't support capabilities and that's ok
[ 0 = "$(getcap -r / | wc -l)" ]
