#!/bin/bash -efu

PROG="${0##*/}"
rc=0

for login in ${INFO_USER_CREATE-}; do
	if id "$login" >/dev/null 2>&1; then
		printf >&2 '%s: ERROR: user "%s" already exist\n' "$PROG" "$login"
		rc=1
		continue
	fi

	eval "uid=\"\${INFO_USER_UID_${login}-}\""
	eval "gid=\"\${INFO_USER_GID_${login}-}\""
	eval "shell=\"\${INFO_USER_SHELL_${login}-}\""
	eval "groups=\"\${INFO_USER_GROUPS_${login}-}\""
	eval "need_hasher=\"\${INFO_USER_HASHER_${login}-}\""

	[ -z "$gid" ] ||
		groupadd -g "$gid" "$login"

	useradd -F \
		${uid:+--uid "$uid"} \
		${gid:+--gid "$gid"} \
		${shell:+--shell "$shell"} \
		${groups:+--groups "$groups"} \
		"$login"

	mkdir -p "/home/$login"
	chmod 0000 "/home/$login"

	case "${need_hasher,,}" in
		yes|true|1)
			hasher-useradd "$login"
			;;
	esac
done

#usermod --home /home/root root
sed -i -r -e '/^root:x:0:0:/{ s@:/root:@:/home/root:@ }' /etc/passwd

exit $rc
