#!/bin/sh -efu

for s in sshd gpm consolelocker chronyd powertop apt-get-update lxd hasherd rsyncd.socket getty@tty1 getty@tty2 getty@tty3; do
	systemctl enable "$s"
done

for s in geoclue lvm2-monitor wpa_supplicant systemd-binfmt; do
	systemctl mask "$s"
done
