#!/bin/sh -efu

for s in sshd gpm consolelocker chronyd powertop hasher-privd rsyncd.socket getty@tty1 getty@tty2 getty@tty3; do
	systemctl enable "$s"
done

for s in altlinux-openresolv altlinux-openresolv.path altlinux-simpleresolv altlinux-simpleresolv.path geoclue lvm2-monitor systemd-binfmt wpa_supplicant; do
	systemctl mask "$s"
done
