#!/bin/sh -efu

[ -x /sbin/systemd ] || [ -x /usr/lib/systemd/systemd ] ||
	exit 0

for s in ${INFO_SYSTEMD_ENABLE_SERVICES-}; do
	systemctl enable "$s"
done

for s in ${INFO_SYSTEMD_MASK_SERVICES-}; do
	systemctl mask "$s"
done
