#!/bin/sh -efu

if [ -L /var/db/repos ]; then
	rm -f -- /var/db/repos
elif [ -d /var/db/repos ]; then
	rm -rf -- /var/db/repos
else
	exit 0
fi

mkdir -p -- \
	/sysimage/cache/gentoo/repos
ln -s -- \
	/sysimage/cache/gentoo/repos \
	/var/db/repos
