#!/bin/sh -eu

PROG="${0##*/}"
date="$(date +%F)"

dir=/mnt/pvt/system
mountpoint -q "$dir" || {
	echo "$PROG: $dir: is not a mountpoint" >&2
	exit 1
}

umask 077
tar -cvP \
	--exclude '*~' \
	--exclude '/mnt/pvt/bootloader/*' \
	--exclude '/mnt/pvt/system/*' \
	-f "$dir"/system-static-"$date".tar \
	/mnt/pvt \
	/usr/local/bin/update_system_static \
	/var/lib/dbus/machine-id /etc/machine-id \
	/etc/hostname \
	/etc/hosts \
	/etc/fstab /etc/crypttab \
	/etc/systemd/network/*.link \
	/etc/systemd/network/*.network \
	/etc/modules-load.d/modules.conf \
	/etc/sysctl.d/99-sysctl.conf \
	/etc/openssh/ssh_host_*_key* \
	/etc/tcb/root/shadow /etc/tcb/gleb/shadow /etc/tcb/doppel/shadow \
	/etc/chrony.conf \
	/etc/apt/sources.list \
#

ln -snvf system-static-"$date".tar "$dir"/system-static.tar

exit 0
