#!/bin/sh -efu

targetdir="$1"; shift
scriptname="$1"; shift

[ -d "$targetdir" ] || targetdir=

cat > "$scriptname" <<EOF
#!/bin/sh -efu

if [ "\$#" -eq 1 ] && [ "\$1" = -h ]; then
	echo "Usage \$0 [<destdir>]"
	exit
fi
if [ -n "$targetdir" ]; then
base64 -d <<__PAYLOAD__ | /.host/cpio -id -D "\${1:-/}"
EOF
[ -z "$targetdir" ] ||
	( cd "$targetdir" && find . -mindepth 1 -print | cpio -o | base64 ) >> "$scriptname"
cat >> "$scriptname" <<EOF
__PAYLOAD__
fi
EOF
chmod +x -- "$scriptname"
