#!/bin/sh

set -eu

FEATURES="-news -ipc-sandbox -network-sandbox -pid-sandbox"
FEATURES="$FEATURES parallel-fetch parallel-install -merge-wait -ebuild-locks"
FEATURES="$FEATURES -collision-detect -protect-owned"
export FEATURES

emerge_common=( -q --ask=n --verbose-conflicts )
emerge_automask=( --autounmask=y --autounmask-write=y --autounmask-use=y --autounmask-continue=y )
emerge_changed_use=( --newuse --changed-use --changed-slot --changed-deps )
emerge_binpkgs=( --usepkg=y --buildpkg=y --binpkg-respect-use=y --rebuilt-binaries=y )
emerge_parallel=( --jobs=12 )

set -- "${emerge_common[@]}" "${emerge_automask[@]}" "${emrege_changed_use[@]}" "${emerge_parallel[@]}"
set -- "$@" "${emerge_binpkgs[@]}"

exec emerge "$@" \
	dev-vcs/git \
	app-portage/gentoolkit \
#
